- name: "Install perl version perl V5.16.3 "
  hosts: localhost
  become: true
  tasks:
    - name: Install prerequisites
      package:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - tar
        - make
        - build-essential
        - libtest-simple-perl
        - gcc
    - name: download the version 5.16.3
      ansible.builtin.get_url:
        url: "https://www.cpan.org/src/5.0/perl-5.16.3.tar.bz2"
        dest: "/tmp/perl-5.16.3.tar.bz2"
    - name: unzip
      ansible.builtin.unarchive:
        src: "/tmp/perl-5.16.3.tar.bz2"
        dest: "/tmp"
        remote_src: yes
        creates: "/tmp/perl-5.16.3"
    - name: Configure Perl
      ansible.builtin.shell: |
        cd /tmp/perl-5.16.3
        ./Configure -des -Dprefix=/usr/local/perl-5.16.3
        make
        make test
        make install
      become: yes
